version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: "weekly"
  assignees:
    - "Competitive-Cyber-Clubs/admins"
  commit-message:
    prefix: "Pip Update"
  reviewers:
    - "Competitive-Cyber-Clubs/admins"