version: 2
checks:
  method-complexity:
      config:
        threshold: 10
  file-lines:
    config:
      threshold: 300
plugins:
  sonar-python:
    enabled: true
    checks:
      python:S1542:
        enabled: false
      python:S3776:
        enabled: false
  pep8:
    enabled: true
  bandit:
    enabled: true
  fixme:
    enabled: true
