stages:
- Code_Check
- test

include:
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Management.gitlab-ci.yml

gemnasium-python-dependency_scanning:
  stage: test
  before_script:
    - which pg_config
    - fine / -name "pg_config"
  services:
  - postgres:latest



.check:
  stage: Code_Check
  script:
    - pip install -r requirements.txt --quiet
    - pip install pylint flake8 --quiet
    - pylint --ignored-classes=_socketobject CCC_Bot.py ./utils/
    - flake8 CCC_Bot.py ./utils/ --statistics --show-source
python-3.5:
  extends: ".check"
  image: python:3.5

python-3.6:
  extends: ".check"
  image: python:3.6

python-3.7:
  extends: ".check"
  image: python:3.7

python-3.8:
  extends: ".check"
  image: python:3.8

pypy-3:
  extends: ".check"
  image: pypy:3

staging:
  stage: test
  image: ruby:latest
  before_script:
  - gem install dpl
  script:
  - dpl --provider=heroku --app=ccc-discord-bot-staging --api-key=$HEROKU_API
  only:
    refs:
      - master
