stages:
- Code_Check
- test

include:
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Management.gitlab-ci.yml



.check:
  stage: Code_Check
  script:
    - pip install -r requirements.txt --quiet
    - pip install pylint flake8 --quiet
    - pylint --ignored-classes=_socketobject CCC_Bot.py ./utils/
    - flake8 CCC_Bot.py ./utils/ --statistics --show-source

python-3.5:
  extends: ".check"
  image: python:3.5-slim

python-3.6:
  extends: ".check"
  image: python:3.6-slim

python-3.7:
  extends: ".check"
  image: python:3.7-slim

python-3.8:
  extends: ".check"
  image: python:3.8-slim

pypy-3:
  extends: ".check"
  image: pypy:3-slim

staging:
  stage: test
  image: ruby:latest
  before_script:
  - gem install dpl
  script:
  - dpl --provider=heroku --app=ccc-discord-bot-staging --api-key=$HEROKU_API
  only:
    refs:
      - master
