stages:
- test

include:
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Management.gitlab-ci.yml

.check:
  script:
    - pip install -r requirements.txt --quiet
    - pip install pylint flake8 --quiet
    - pylint --ignored-classes=_socketobject CCC_Bot.py ./utils/
    - flake8 CCC_Bot.py ./utils/ --statistics --show-source
python-3.5:
  extends: ".check"
  stage: test
  image: python:3.5

python-3.6:
  extends: ".check"
  stage: test
  image: python:3.6

python-3.7:
  extends: ".check"
  stage: test
  image: python:3.7

python-3.8:
  extends: ".check"
  stage: test
  image: python:3.8

pypy-3:
  extends: ".check"
  stage: test
  image: pypy:3
