stages:
- test

include:
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml
  - template: Secret-Detection.gitlab-ci.yml

variables:
    DS_DEFAULT_ANALYZERS: "gemnasium"
    CI_DEBUG_TRACE: "true"

license_scanning:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - requirements.txt
        - requirments-dev.txt