stages:
- Code_Check
- test

include:
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml
  - template: Secret-Detection.gitlab-ci.yml

license_scanning:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - requirements.txt
        - requirments-dev.txt



.check:
  stage: Code_Check
  before_script:
    - pip install -r requirements-dev.txt --quiet
  script:
    - pylint --rcfile tox.ini CCC_Bot.py ./utils/ ./cogs/
    - flake8 CCC_Bot.py ./utils/ ./cogs/ --statistics --show-source
    - bandit -r ./CCC_Bot.py ./cogs/ ./utils/
    - black --check --line-length 100 .

python-3.6:
  extends: ".check"
  image: python:3.6

python-3.7:
  extends: ".check"
  image: python:3.7

python-3.8:
  extends: ".check"
  image: python:3.8