# fly.toml file generated for ccdc-bot on 2022-10-22T17:17:47-04:00

app = "staging-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []
services = []


[env]
  LOG_LEVEL = "DEBUG"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  cmd = []
  entrypoint = []
  exec = []
