name: Build & Check

on: [push]


jobs:

  Python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('**/requirements.txt', '**/requirements-dev.txt') }}

    - name: Install dependencies
      run: |
        pip install -U pip wheel setuptools --quiet
        pip install -r requirements-dev.txt

    - name: Lint with Black, Pylint, Flake8, and Bandit
      run: make lint

  Deploy:
    runs-on: ubuntu-latest
    needs: Python
    steps:
    - uses: actions/checkout@v3

    - name: Set Deployment
      run: |
        if [ "$REF" == "true" ]; then
          echo "DEPLOYMENT=--app ccc-bot" >> $GITHUB_ENV
        fi
      env:
        REF: ${{ startsWith(github.ref, 'refs/tags/v') }}

    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --local-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
#
#    - run: make ${{ env.DEPLOYMENT }}
#      env:
#        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}